version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm cit
  publish_to_npm:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm publish
  
workflows:
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish_to_npm:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
